from .base_page import Page
from .product_page import ProductPage
from .catalog_page import CatalogPage
from .receipt_page import ReceiptPage   
from .invoice_page import InvoicePage
from .cart_page import CartPage
from .login_page import LoginPage
from .register_page import RegisterPage
from .main_page import MainPage